apiVersion: v1
kind: ReplicationController
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: python
      version: v1
      role: vote
    matchExpressions: 
      - {key: version, operator: In, values: [v1, v2, v3]}  
  template:
    metadata:
      name: vote
      labels:
        app: python
        verion: v1
        role: vote
    spec:
      containers:
      - name: app
        image: schoolofdevops/vote:v1
  
