apiVersion: v1
kind: ReplicationController
metadata: 
  name: echoheaders # Name of the Replica Controller
spec:
  replica: 10
  selector:
    app: static-site-pod  # name of the pod which will be used by replica controller to create the replica
  template:
    metadata:
      labels:
        apps: static-site-pod   # Name pod - if pod not found this name will be used for the created pod
    spec:
      containers:
      - name: hello   # Name of the container (name doesn't matter) if pod doesn't exist it will be created using this image.
        image: docker.io/seqvence/static-site:latest
        ports:
          - containerPort: 80
