apiVersion: v1
kind: ReplicationController
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 4
  selector:
    app: pthon
    version: v1
    role: vote
  template:
    metadata:
      name: vote
      labels:
        app: python
        verion: v1
        role: vote
    spec:
      containers:
      - name: app
        image: schoolofdevops/vote:v1
  
